config/routes.rb
SampleApp::Application.routes.draw do

  resources :users
  resources :sessions, only: [:new, :create, :destroy]

  match '/authenticate/',     to: 'users#authenticate'
  match '/signup',            to: 'users#new'
  match '/signin',            to: 'sessions#new'
  match '/signout',           to: 'sessions#destroy', via: :delete

  
  match "/location",          to: "trackers#location"
  match "/view",              to: "trackers#view"
  match '/edit',             to: "trackers#edit"
  match "/update",            to: "trackers#update"
  match "/trackers",          to: "trackers#index"
  match "/options",           to: "trackers#options"
  match "/geoloc",            to: "trackers#geoloc"

  root to: 'static_pages#home'
  
  match '/help',              to: 'static_pages#help'

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="http://www.sparksoft.com.ph/">Developed by SparkSoft Solutions Inc.
  </small>
  <!--<nav>
    <ul>
      
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>-->
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "sample app", '#', id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Home",    root_path %></li>
          <li><%= link_to "Help",    help_path %></li>
          <li><%= link_to "Sign in", '#' %></li>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_header2.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
       <%= link_to "vehicle tracker", {:controller => "trackers", :action => "view", :user_index => current_user.id}, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Track", {:controller => "trackers", :action => "view", :user_index => current_user.id} %></li>
          <li><%= link_to "How To", help_path %></li>
          <% if signed_in? %>
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Edit Bounds", {:controller => "trackers", :action => "edit", :user_index => current_user.id} %></li>
                <li><%= link_to "Options", '' %></li>
                <li class="divider"></li>
                <li><%= link_to "Profile", current_user %></li>
                <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Sign out", signout_path, method: "delete" %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Sign in", signin_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <meta name="viewport" content="initial-scale=1.0, user-scalable=no" />
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>    
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>